:numbered!:
== License

(C) Copyright 2016, Amelia Read Garripoli

Amelia Read Garripoli (agarripoli@olympic.edu) +
Information Systems +
Department of Business &amp; Technology +
Olympic College +
Bremerton, WA 98337

Like those that came before it, this book can be distributed in unmodified form for non-commercial purposes. Modified versions can be made and distributed for non-commercial purposes provided they are distributed under the same license as the original. More specifically: This work is licensed under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 License. To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-sa/4.0/. Other uses require permission from the author.

The website for this book is: http://faculty.olympic.edu/agarripoli/New2ASP .

This book is provided “as-is”. It may contain errors of spelling, grammar, or semantics. Information and views expressed in this document may change without notice. You bear the risk of using it.
Examples depicted herein are provided for illustration only and are fictitious. 

This book references websites from external sources not under my control. The web addresses may change, the content may change, and in particular they may have an invasive privacy policy. It is your responsibility to be aware of this and to act accordingly. You use the links in this text at your own risk. 

Use shall constitute acceptance of the terms listed.

Microsoft, Windows, Visual Studio, IIS, and ASP.NET are either registered trademarks or trademarks of Microsoft Corporation in the United States and/or other countries.

:numbered!:
== Dedication

This book is dedicated to my family for not minding me doing this project while on summer break; to my peers at Olympic College, for giving me this opportunity; and to all the developers I have enjoyed working with in the past -- isn't it crazy how the internet has taken over every facet of what we do?

:numbered!:
== Preface

I wrote this book over my 2016 summer break, off-contract from my position as tenure-track Information Systems Faculty at Olympic College, using only personal resources. My goal was to make the Introduction to ASP.NET class something approachable without requiring a heavy math background or a career in software development. It assumes that you have had some programming courses and written small (100-line or more) programs successfully in an object-oriented language (such as Java or JavaScript); put together multi-page websites in HTML and CSS succcessfully; have used SQL in database systems; and desire to learn the ASP.NET environment.

Due to time constraints, I've made heavy use of excellent OER resources written for Java; C# and Java share many similarities. That said, this could not have been accomplished without the excellent Microsoft Developer's Network resources at http://www.asp.net/ and http://www.msdn.com/

This book will be covering Razor, C#, and the ASP.NET library. It assumes you have already taken these Olympic College courses:

* CIS 155, Web Development I. This course covers HTML and CSS.
+
If you need a refresher on HTML, I recommend the Microsoft Academy course, https://mva.microsoft.com/en-US/training-courses/html5-css3-fundamentals-development-for-absolute-beginners-14207[HTML5 & CSS3 Fundamentals: Development for Absolute Beginners]

* CIS 210, Introduction to SQL. This course covers SQL.
+
If you need a refresher on SQL, I recommend http://sqlzoo.net/[SQLZoo's Tutorial] or Learn Code The Hard Way's http://sql.learncodethehardway.org/[Learn SQL The Hard Way].

* Either CIS 255, Web Development II, which covers programming in JavaScript, or CIS 142, Java Programming I, which covers OO programming in Java.
+
If you need a refresher on programming, I recommend finding a "learn to program" course on Java or C# on Udemy, EdX, Coursera, or other platform. (If you have a specific one you recommend, let me know). 

It's always a good idea to know the history behind what you are learning, so here is a short look into the history behind this technology:

ASP.NET was first released in 2002 by Microsoft as a web application framework on top of the .NET platform (first released in 2000), their common framework and engine for several programming languages. It provides a library and framework to support web development, and replaced the earlier Active Server Pages tehnology developed by Microsoft.

Razor was developed in 2010 by Andrew Nurse (http://vibrantcode.com/) for Microsoft it replaces Active Server Pages' (.aspx's) inlining syntax with a simpler form that has been embraced by the Microsoft developer community. It streamlines the transition between HTML and code.

C# was developed in 1999 by Microsoft. Who designed paticular features we do not know, but the team lead was Anders Hejlsberg. If you know Java, some of the changes may seem silly (IndexOutOfBoundsException instead of ArrayIndexOutOfBoundsException, for example) but some changes are helpful -- the foreach loop in C# resulted in the definition of a similar structure in Java, after C# did it. C# also introduced many helpful shorthands in defining classes, so properties really are properties, and not directly tied to class instance variables. Was C# a response to Java's license requiring no changes to Java? we will never know, but its lead developer claims that C# is "not a Java clone" but is more related to C++.

For more background, see

- https://en.wikipedia.org/wiki/.NET_Framework
- https://en.wikipedia.org/wiki/ASP.NET
- https://en.wikipedia.org/wiki/ASP.NET_Razor
- https://en.wikipedia.org/wiki/C_Sharp_(programming_language)


