[preface]
:numbered!:
== Preface

I wrote this book over my 2016 summer break, off-contract. My goal was to make the Introduction to ASP.NET class something approachable without requiring a heavy math background or a career in software development. It assumes that you have had some programming courses and written small (100-line or more) programs successfully in an object-oriented language (such as Java or JavaScript); put together multi-page websites in HTML and CSS succcessfully; have used SQL in database systems; and desire to learn the ASP.NET environment.

Due to time constraints, I've made heavy use of excellent OER resources written for Java; C# and Java share many similarities. That said, this could not have been accomplished without the excellent Microsoft Developer's Network resources at http://www.asp.net/ and http://www.msdn.com/

This book will be covering Razor, C#, and the ASP.NET library.

If you need a basis in HTML, I recommend the Microsoft Academy course, https://mva.microsoft.com/en-US/training-courses/html5-css3-fundamentals-development-for-absolute-beginners-14207[HTML5 & CSS3 Fundamentals: Development for Absolute Beginners]

If you need a basis in SQL, I recommend http://sqlzoo.net/[SQLZoo's Tutorial] or Learn Code The Hard Way's http://sql.learncodethehardway.org/[Learn SQL The Hard Way].

It's always a good idea to know the history behind what you are learning, so here is a short look into the history behind this technology:

ASP.NET was first released in 2002 by Microsoft as a web application framework on top of the .NET platform (first released in 2000), their common framework and engine for several programming languages. It provides a library and framework to support web development, and replaced the earlier Active Server Pages tehnology developed by Microsoft.

Razor was developed in 2010 by Andrew Nurse (http://vibrantcode.com/) for Microsoft it replaces Active Server Pages' (.aspx's) inlining syntax with a simpler form that has been embraced by the Microsoft developer community. It streamlines the transition between HTML and code.

C# was developed in 1999 by Microsoft. Who in particular designed features we do not know, but the team lead was Anders Hejlsberg. If you know Java, some of the changes may seem silly (IndexOutOfBoundsException instead of ArrayIndexOutOfBoundsException, for example) but some changes are helpful -- the foreach loop in C# resulted in the definition of a similar structure in Java, after C# did it. C# also introduced many helpful shorthands in defining classes, so properties really are properties, and not directly tied to class instance variables. Was C# a response to Java's license requiring no changes to Java? we will never know, but its lead developer claims that C# is "not a Java clone" but is more related to C++.

For more background, see

- https://en.wikipedia.org/wiki/.NET_Framework
- https://en.wikipedia.org/wiki/ASP.NET
- https://en.wikipedia.org/wiki/ASP.NET_Razor
- https://en.wikipedia.org/wiki/C_Sharp_(programming_language)
